name: Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env: 
  DOCKER_IMAGE: chonalchendo/footcrawl
  TAG: latest
concurrency:
  cancel-in-progress: true
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: ./.github/actions/setup
      - run: uv sync --only-dev
      - run: uv run just check-test
      - run: uv run just package
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the GitHub Container Registry (ghcr)
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GK_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

